---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue-service
  labels:
    app: productcatalogue
spec:
  type: NodePort
  selector:
    app: productcatalogue
  ports:
  - protocol: TCP
    port: 8020
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue-deployment
spec:
  selector:
    matchLabels:
      app: productcatalogue
  replicas: 1
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue-container
        image: thetips4you/productcatalogue:latest
        ports:
        - containerPort: 8020
        resources:
          limits:
            cpu: "0.5"  # Set the desired CPU limit
            memory: "512Mi"  # Set the desired memory limit
          requests:
            cpu: "0.2"  # Set the desired CPU request
            memory: "256Mi"  # Set the desired memory request
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
